### ISSUE TITLE
Which files can be browsed in the Shiny app?

### ISSUE THREAD

**Issue by francoiskroll** [brlauuu/seurat_exploration#2]
Thank you for providing the Shiny app to browse the data!

Would it be possible to add a couple of examples or specify exactly which files from the GEO can be browsed in the Shiny app?

After a lot of troubleshooting installing Seurat, URD, and all of their dependencies so everything was happy to work together, I am now using:

    R 3.6.3
    Seurat 2.3.4
    URD 1.1.1

I can launch the Shiny app, but I cannot load any files successfully.

#### Seurat

Not knowing exactly what you call Seurat files from the GEO; I have tried:

`GSE158142_zf5dpf_cc_filt.cluster.rds`
> Invalid Seurat file loaded

`GSE158142_zf15dpf_PCAALL.rds`
> Invalid Seurat file loaded

`GSE158142_tree-hypoND_knn-100_sigma-8_40F-80B_NO-_ks_0001.rds`
> Invalid Seurat file loaded

#### URD
I have tried loading what I imagine is an URD file: `GSE158142_URD_hypoND.rds` (in the URD tab of the Shiny app)

> Warning: Error in plotTree: A tree has not been calculated for this URD object. buildTree must be run first.

What am I doing wrong?

____

#### Edit1

* I am now able to open files `GSE158142_tree-hypoND_knn-100_sigma-8_40F-80B_NO-_ks_0001.rds` and `GSE158142_tree-retinanewnokND_knn-140_sigma-14_40F-80B_NO-15d-29-15d-39-15d-43-15d-62_pref_01.rds` in the URD tab of the Shiny app.

* I have tried loading `GSE158142_zf24hpf_cc_filt.cluster.rds` into R (with `readRDS()`), and it says it is:

    > An object of class seurat in project zf24hpf 
        19615 genes across 9105 samples.

   So looks like a valid Seurat file? However, I am still not able to browse it through the Shiny app (`Invalid Seurat file loaded`).

**Comment by brlauuu** [comment]
Hi @francoiskroll,

Thanks for reaching out.

Firstly, I would recommend using Seurat 4+ unless you have certain dependencies on v2.3.4. Both work with our data though.

Secondly, as you noticed, when you try to load URD file in Seurat tab, you'll get that error and the same goes if you try to load Seurat file in URD tab. So hence the errors you were getting.

Thirdly, your issue made me realize that there is a bug in the code which creates the error you mention. A quick fix you can apply is to rename the downloaded file from `GSE158142_zf24hpf_cc_filt.cluster.rds` to `zf24hpf_cc_filt.cluster.rds`. It's essentially just removing the prefix of the GSE ID. That should solve your issue. You can find the full list of mappings in the file [stage_time_clustering_res_mapping.tsv](https://github.com/brlauuu/zf_brain/blob/master/data/stage_time_clustering_res_mapping.tsv).

This is in fact a bug and I will add it as a separate issue. However, it does not seem urgent at the moment since it can be fixed with simple rename of the file.

Let me know if you have any additional issues.

**Comment by brlauuu** [comment]
Actually, I just added a quick fix for your case so you don't have to rename anything yourself. Just make sure you have the latest version of the code.

Thanks again for reporting this issue and feel free to write me if you have any additional questions.

I will close this issue since it is solved.

**Comment by francoiskroll** [comment]
I can confirm it's working now. Thank you!
